name: Secret Scan

on:
  push:
    branches: ['*']   # run on all branches
  pull_request:       # also run on all PRs

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
